version: "3"
services:
  moneyprinterplus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["python3", "Backend/main.py"]
    volumes:
      - ./files:/temp
      - ./Backend:/app/Backend
      - ./Frontend:/app/Frontend
      - ./fonts:/app/fonts
    environment:
      - ASSEMBLY_AI_API_KEY=${ASSEMBLY_AI_API_KEY}
      - TIKTOK_SESSION_ID=${TIKTOK_SESSION_ID}
      - IMAGEMAGICK_BINARY=/usr/bin/convert
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - COQUI_TTS_URL=${COQUI_TTS_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always

volumes:
  files:
